### ISSUE TITLE
Copyright issue in the LICENSE

### ISSUE THREAD

**Issue by akien-mga** [cobrapitz/GraphicsEditor#1]
Hi @cobrapitz,

I was reviewing your asset submission for the Godot Asset Library, but I see that this is a fork of @Flairieve's https://github.com/Flairieve/GraphicsEditor, yet their copyright statement has not been kept in your license.

Both projects use the MIT license which is fine, but the copyright statement is still valid and should be kept (as required by the very terms of the MIT license).

So the copyright statement for your fork should be:
```
Copyright (c) 2019 Flairieve
Copyright (c) 2020 cobrapitz
```

**Comment by cobrapitz** [comment]
Hi @akien-mga,

thank you for taking the time to review the asset and pointing that out, i thought the fork would be enough.
I updated the license file and the submission to the asset library to the latest commit.

**Comment by akien-mga** [comment]
Thanks, fixed by 0d0adcc4fd.
