### ISSUE TITLE
Unable to export png

### ISSUE THREAD

**Issue by Ezenki** [cobrapitz/GraphicsEditor#3]
The export as png doesn't really work, it exports something but this cant be used as a sprite for my game.
this fork is definitely better IMO, I hope you continue to improve this when you have time.

**Comment by cobrapitz** [comment]
Hey, thank you for trying it, can u try the dev branch, if that fixes it or show the steps to reproduce this? (Sorry for not responding didn't get any notification apparently)

**Comment by cobrapitz** [comment]
I have recently updated the addon on the assetlib, if you still have this issue, then please feel free to reopen the issue.
Ty!
