### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by nice-shot** [cobrapitz/GraphicsEditor#4]
Hello,
What is the project's current status in terms of additional development and responses to issues and PRs?
I'm interested in adding PRs for bugfixes and additional features but I'd like to know if the owner will be able to review and respond to them?

Thanks!

**Comment by cobrapitz** [comment]
Hey thank you for posting.

I am probably not developing this further as it didn't reach the performance (especially for drawing brushes with Bresenham) I wanted it to have.
But I can definitely review and respond to them.

**Comment by Salvakiya** [comment]
this is too bad as this would be a fantastic addition...
