### ISSUE TITLE
request move sprite canvas closer to reachable

### ISSUE THREAD

**Issue by zachthemystic** [cobrapitz/GraphicsEditor#5]
This is a minor improvement request. I'm new to godot. I thought it would be cool to have a built-in sprite editor, so I searched the public assets and found this. I've read a recent comment and I realize that this plugin may not continue because of slow performance. But I wanted to leave brief feedback since I tried it out and now I'm moving on other draw tools.

Currently the draw canvas is in the middle of emptiness, too distant from any other tools, so it's annoying. A small improvement would be to put it at the upper left or at least nearer to some tools. This is a very easy "low hanging fruit" fix. Little improvements like this could get the user interface to the point where it's at least fun to play with. If a few people enjoy it, even if it's slow, it might find a place for people who just want to fix a sprite quickly without leaving godot.

That's it. That's my little bit of feedback. Cheers!

**Comment by cobrapitz** [comment]
Hey, thank you for leaving feedback.

Can you explain what exactly you mean with "in the middle of emptiness"?

It should be in the middle of the screen and you can scroll/move with middle mouse button.

**Comment by zachthemystic** [comment]
I just mean the simplest fact that when I wanted to draw on it I had to
move the mouse into the middle of the big window where there was nothing
surrounding it. Quite a distance from any of the tool buttons. Like, if the
draw canvas and the tools were at least nearer to each other
(solution: make the window moveable, resizable, or place the canvas closer
to the tools by default), I would have spent more time investigating the
other features.

**Comment by zachthemystic** [comment]
Okay I just tried your suggestion. I got the window to move by zooming in
and out. So it's possible at least!

**Comment by zachthemystic** [comment]
Okay also found the middle mouse button. Works. (I haven't had to use that
button on other apps so I didn't think to try it.) Alright, I'll see what
else I can critique!

**Comment by zachthemystic** [comment]
Okay, my next criticism is that I can't see the brush size. The only way I
found to change it was to click on it, where it changed color and seemed to
cycle through only 4 or 5 types. I'd like a clear indicator of brush size
and a way to change the diameter (preferably with one click using a slider,
e.g.). That would be my next improvement.

**Comment by cobrapitz** [comment]
I see. On the other branch I have an updated version. I didn't upload it to the asset store though.
If you wouldn't mind, you could download the other version and try that.

**Comment by zachthemystic** [comment]
Ok, I downloaded it.

And I can change the brush size! I'll let you know if anything else seems
like an obvious quick fix. Thanks.

**Comment by cobrapitz** [comment]
Ok ty for your feedback so far. :D 

I will close this issue, just open another one if you have more feedback.
